### ISSUE TITLE
The human body parts corresponding to the key points

### ISSUE THREAD

**Issue by bwshen93** [aleflabo/MoCoDAD#12]
Thank you for sharing. May I ask which part of the human body corresponds to the 17 key points of human bones in the dataset? Do you have any relevant reference instructions or pictures? May I ask if the key points of human bones are inherent in the dataset? How was the trajectory data obtained

**Comment by aleflabo** [comment]
Hi! 

Thank you for your interest in our work. 
As also done for the HR-Avenue and HR-STC datasets, the sequences are extracted using alphapose for the pose estimation and poseflow for tracking people in the videos. The 17 keypoints are in the COCO format.

**Comment by aleflabo** [comment]
Hi!

We added the code that we used to annotate UBnormal. Please refer to [this README](https://github.com/aleflabo/MoCoDAD/tree/main/_annotations#code-for-generating-the-annotations-with-alphaposeposeflow) for further details.
