### ISSUE TITLE
Dataset preparation

### ISSUE THREAD

**Issue by 213pk** [aleflabo/MoCoDAD#13]
Hi, if I want to process my original video dataset to become the skeleton information (same as the form of your input), how to generate the input? I only have the original avi. files. Besides, how do I annotate them? Thanks!

**Comment by aleflabo** [comment]
Hi! 

As described in the paper and in the issue [here](https://github.com/aleflabo/MoCoDAD/issues/12#issuecomment-2195315005), we used alphapose and poseflow to extract the skeletons and to follow people in the videos.

**Comment by stdrr** [comment]
Hi! 

We added the code that we used to annotate UBnormal. Please refer to [this README](https://github.com/aleflabo/MoCoDAD/tree/main/_annotations#code-for-generating-the-annotations-with-alphaposeposeflow) for further details.
