### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by HJL-cv** [aleflabo/MoCoDAD#14]
Hi！
Thank you for sharing.I would like to ask how to obtain the .csv file and the .npy file when preparing a custom dataset.

**Comment by aleflabo** [comment]
Hi!

We added the code that we used to annotate UBnormal. Please refer to [this README](https://github.com/aleflabo/MoCoDAD/tree/main/_annotations#code-for-generating-the-annotations-with-alphaposeposeflow) for further details.

**Comment by HJL-cv** [comment]
I tried using the Dockerfile you provided, but encountered the error: 'nvidia/cuda:11.6.0-runtime-ubuntu20.04 not found.' Could it be that this image version has been removed?

**Comment by HJL-cv** [comment]
> Hi!
> 
> We added the code that we used to annotate UBnormal. Please refer to [this README](https://github.com/aleflabo/MoCoDAD/tree/main/_annotations#code-for-generating-the-annotations-with-alphaposeposeflow) for further details.
Hi！
I followed the method you provided, and while working with the Dockerfile, I encountered an issue where the image source ’nvidia/cuda:11.6.0-runtime-ubuntu20.04‘ did not exist. So, I replaced it with the ‘nvidia/cuda:11.6.1-runtime-ubuntu20.04’ image source, but then I encountered the following error:
ERROR:failed to solve: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends     libtinfo5 libncursesw5     cuda-cudart-dev-11-6=${NV_CUDA_CUDART_DEV_VERSION}     cuda-command-line-tools-11-6=${NV_CUDA_LIB_VERSION}     cuda-minimal-build-11-6=${NV_CUDA_LIB_VERSION}     cuda-libraries-dev-11-6=${NV_CUDA_LIB_VERSION}     cuda-nvml-dev-11-6=${NV_NVML_DEV_VERSION}     ${NV_LIBNPP_DEV_PACKAGE}     libcusparse-dev-11-6=${NV_LIBCUSPARSE_DEV_VERSION}     ${NV_LIBCUBLAS_DEV_PACKAGE}     ${NV_LIBNCCL_DEV_PACKAGE}     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

Could you please advise me on how to resolve this issue? I look forward to your response.

**Comment by HJL-cv** [comment]
> Hi!
> 
> We added the code that we used to annotate UBnormal. Please refer to [this README](https://github.com/aleflabo/MoCoDAD/tree/main/_annotations#code-for-generating-the-annotations-with-alphaposeposeflow) for further details.

Hi！
I followed the method you provided, and while working with the Dockerfile, I encountered an issue where the image source ’nvidia/cuda:11.6.0-runtime-ubuntu20.04‘ did not exist. So, I replaced it with the ‘nvidia/cuda:11.6.1-runtime-ubuntu20.04’ image source, but then I encountered the following error:
ERROR:failed to solve: process "/bin/sh -c apt-get update && apt-get install -y --no-install-recommends libtinfo5 libncursesw5 cuda-cudart-dev-11-6=${NV_CUDA_CUDART_DEV_VERSION} cuda-command-line-tools-11-6=${NV_CUDA_LIB_VERSION} cuda-minimal-build-11-6=${NV_CUDA_LIB_VERSION} cuda-libraries-dev-11-6=${NV_CUDA_LIB_VERSION} cuda-nvml-dev-11-6=${NV_NVML_DEV_VERSION} ${NV_LIBNPP_DEV_PACKAGE} libcusparse-dev-11-6=${NV_LIBCUSPARSE_DEV_VERSION} ${NV_LIBCUBLAS_DEV_PACKAGE} ${NV_LIBNCCL_DEV_PACKAGE} && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
Could you please advise me on how to resolve this issue? I look forward to your response.

**Comment by stdrr** [comment]
Hi! Thank you for being so interested in the annotation process.

The error you're getting is perhaps due to a version mismatch between the cuda-runtime image and the variables set in the Dockerfile. You can try to modify the file accordingly:

```dockerfile
ENV NV_CUDA_LIB_VERSION "11.6.1-1"

FROM base as base-amd64

ENV NV_CUDA_CUDART_DEV_VERSION 11.6.55-1
ENV NV_NVML_DEV_VERSION 11.6.55-1
ENV NV_LIBCUSPARSE_DEV_VERSION 11.7.2.112-1
ENV NV_LIBNPP_DEV_VERSION 11.6.2.112-1
ENV NV_LIBNPP_DEV_PACKAGE libnpp-dev-11-6=${NV_LIBNPP_DEV_VERSION}

ENV NV_LIBCUBLAS_DEV_VERSION 11.8.1.74-1
ENV NV_LIBCUBLAS_DEV_PACKAGE_NAME libcublas-dev-11-6
ENV NV_LIBCUBLAS_DEV_PACKAGE ${NV_LIBCUBLAS_DEV_PACKAGE_NAME}=${NV_LIBCUBLAS_DEV_VERSION}

ENV NV_LIBNCCL_DEV_PACKAGE_NAME libnccl-dev
ENV NV_LIBNCCL_DEV_PACKAGE_VERSION 2.12.7-1
ENV NCCL_VERSION 2.12.7-1
ENV NV_LIBNCCL_DEV_PACKAGE ${NV_LIBNCCL_DEV_PACKAGE_NAME}=${NV_LIBNCCL_DEV_PACKAGE_VERSION}+cuda11.6
```

You might also need to import the right keys to access the Nvidia repositories when issuing `apt update`. You can try to add the following command before line 28 of the Dockerfile:

```dockerfile
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
```

You can compare the configuration of your Dockerfile with [this](https://hub.docker.com/layers/nvidia/cuda/11.6.1-devel-ubuntu20.04/images/sha256-2732cd07ffb34d73621a12de8ecea08a1caa7b87d43ccbca34112de189824c20), from which I took the updated environment variables.

Please let me know if this solves the problem, I'm available for further help. 

Stefano

**Comment by HJL-cv** [comment]
Thank you for your response, it has been very helpful to me.
