### ISSUE TITLE
how to visualize 

### ISSUE THREAD

**Issue by iammehdii** [aleflabo/MoCoDAD#15]
hey, thanks for great work
i m using pretrained model, and i want to use visualize.ipynb and it needs some files about anomaly scores which supposed to be in  ./data/ubnormal/saved_clip_scores. how can i generate this files? 

tnx in advanced

**Comment by aleflabo** [comment]
Hi! 

in the ./data/ubnormal/saved_clip_scores folder, you need to store the anomaly scores in npy files. The predicted anomaly scores must have the same shape as the ground truth ones. 

In the notebook you can see the description about the stored npy files:


```
""" 
This code is shown as an example. It assumes that 
1. `base_path` contains the .npy files with the anomaly scores for the clips to visualize; 
2. `ground_truth_path` contains the .npy files with the ground truth masks corresponding to the clips to visualize
"""

base_path = './data/ubnormal/saved_clip_scores/'
scene, clip = (8,2)
model_anomaly_scores_path = base_path + f'error_per_person_scene_{scene}_scenario_{clip}.npy' 
ground_truth_path = f'./data/ubnormal/saved_clip_scores/gt_masks/scene_{scene}_scenario_{clip}.npy'

error_per_person = np.load(model_anomaly_scores_path)
gt = np.load(ground_truth_path)

```

I hope this helps.

**Comment by iammehdii** [comment]
Thank you for your answer, but I wanted to know how I can generate these .npy files. Which .py files do I need to run to create these files and store them in that location? I have executed predict_Mooted.pay and evil_Mooted.pay, and I have read the config.yaml file multiple times, but I still do not understand how to generate them.
Any assistance you can provide would be greatly appreciated. 
Thank you in advance

**Comment by aleflabo** [comment]
You can save all the tensors using the predict_MoCoDAD.py file in the root

**Comment by iammehdii** [comment]
do I need to set any parameters False or True to store them?
Many thanks

**Comment by stdrr** [comment]
Hi!

When you run `predict_MoCoDAD.py`, the output of the model's `forward(..)` are automatically stored in a folder according to [this line](https://github.com/aleflabo/MoCoDAD/blob/51f00b98a17f18180531b98565d49e0e046f2e6c/predict_MoCoDAD.py#L34). You can then generate the `error_per_person_scene_{scene}_clip_{clip}.npy` files by processing the saved model's output similarly to [this function](https://github.com/aleflabo/MoCoDAD/blob/51f00b98a17f18180531b98565d49e0e046f2e6c/models/mocodad.py#L337). Specifically, you have to store the content of [this variable](https://github.com/aleflabo/MoCoDAD/blob/51f00b98a17f18180531b98565d49e0e046f2e6c/models/mocodad.py#L417C13-L417C64).
