### ISSUE TITLE
stuck in the command "docker build -t pose_and_track ."

### ISSUE THREAD

**Issue by 213pk** [aleflabo/MoCoDAD#17]
When I run this command, the terminal shows 
"Step 39/44 : RUN conda install pyyaml==5.2 scipy==1.1.0 pytorch==1.2.0 torchvision==0.4.0     pillow==6.2.1 matplotlib==3.2.2 cython notebook
 ---> Running in efc71d1df408
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working..." 
and it keeps running for many days and no response. How do I solve it? The previous steps are correct. Thanks!

**Comment by stdrr** [comment]
Hi!

Sometimes, `conda` might fail to find the required packages in the default repositories. You may try to append `-c pytorch -c nvidia` at the end of that command. Please also note that the default repositories are not accessible from company servers unless the company has an active subscription. If this is the case, you may override the default repositories with `conda-forge`.
