### ISSUE TITLE
Annotation problem

### ISSUE THREAD

**Issue by 213pk** [aleflabo/MoCoDAD#18]
For the docker file, it uses nvidia/cuda:11.6.0-runtime-ubuntu20.04 as base. Could you provide a version of cuda 12.0? Thanks!

**Comment by stdrr** [comment]
Hi!

Thank you for your interest in our project!

We can't provide and test an updated version, but you may look at issue #14 to see how to adapt the Dockerfile to your needs. You may refer to [this page](https://hub.docker.com/r/nvidia/cuda/tags) to choose a cuda environment version that can fit - you may start with [`12.6.0-cudnn-devel-ubuntu20.04`](https://hub.docker.com/layers/nvidia/cuda/12.6.0-cudnn-devel-ubuntu20.04/images/sha256-defe1a2969b0bcebf1672e94918532956ae4e5596b4ec1293f5f5d0401583efc?context=explore).

I'm available for further help.
