### ISSUE TITLE
Human posture sequence 

### ISSUE THREAD

**Issue by GP0123** [aleflabo/MoCoDAD#2]
how is the historical human posture sequence obtained ?

**Comment by aleflabo** [comment]
Hi,

Following previous methods, the sequences are extracted using alphapose for the pose estimation and poseflow for tracking people in the videos.

**Comment by GP0123** [comment]
Thank you

**Comment by aleflabo** [comment]
Hi!

We added the code that we used to annotate UBnormal. Please refer to [this README](https://github.com/aleflabo/MoCoDAD/tree/main/_annotations#code-for-generating-the-annotations-with-alphaposeposeflow) for further details.
