### ISSUE TITLE
data structure for annotation

### ISSUE THREAD

**Issue by 213pk** [aleflabo/MoCoDAD#20]
For "UBnormal
import shlex
import os
from tqdm import tqdm
import datetime
from glob import glob
from natsort import natsorted

for scene_path in natsorted(glob('../shared_memory/data/*')):
    scene = os.path.basename(scene_path)
    print(scene)
    for clip in tqdm(natsorted(glob(os.path.join(scene_path, 'frames/*')))):

        os.environ['indir'] = shlex.quote(clip)
        os.environ['outdir'] = shlex.quote(os.path.join('../shared_memory/res/', scene, os.path.basename(clip)))
        try: 
            os.makedirs(os.environ['outdir'], exist_ok=True)
        except:
            pass

        !python -W ignore scripts/demo_inference.py \
        --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml \
        --checkpoint ../shared_memory/pretrained_models/fast_res50_256x192.pth --detbatch 1 \
        --posebatch 24 --indir $indir --outdir $outdir --sp

        print('\n#### Start tracking....{}'.format(datetime.datetime.now()))

        !python -W ignore trackers/PoseFlow/tracker-general.py \
        --imgdir $indir \
        --in_json $outdir/alphapose-results.json \generate_annotations.ipynb
        --out_json $outdir/alphapose-results-forvis-tracked.json       " in generate_annotations.ipynb, I would like to know where is the UBnormal data located in. Is it image/frame or video? Thanks!

**Comment by stdrr** [comment]
Dear @213pk, thank you for your interest in our work, and sorry for the late reply.

We are not actively maintaining the code for the dataset annotations, hence we don't guarantee that it will run properly. Furthermore, new updates of Alphapose and new models have been released in the meantime, so I would advise you to look at more recent works. If just the annotations of UBnormal are needed, we have released all the required files in the shared GDrive folder.

Best regards,
Stefano
