### ISSUE TITLE
KeyError: 'new_pid'

### ISSUE THREAD

**Issue by 213pk** [aleflabo/MoCoDAD#21]
I put a video in the file "./shared_memory/data/" and the code for tracking is modified as 
"%load_ext autoreload
%autoreload 2
%cd ./AlphaPose
import shlex
import os
from tqdm import tqdm
import datetime
from glob import glob
from natsort import natsorted
import os

#cwd = os.getcwd()  # Get the current working directory (cwd)
#files = os.listdir(cwd)  # Get all the files in that directory
#print("Files in %r: %s" % (cwd, files))
for scene_path in natsorted(glob('../shared_memory/*')):
    scene = os.path.basename(scene_path)
    print(scene)
    for clip in tqdm(natsorted(glob(os.path.join(scene_path)))):

        os.environ['indir'] = shlex.quote(clip)
        os.environ['outdir'] = shlex.quote(os.path.join('../shared_memory/res/', scene, os.path.basename(clip)))
        print(os.environ['indir'])
        print(os.environ['outdir'])
        
        try: 
            os.makedirs(os.environ['outdir'], exist_ok=True)
        except:
            pass

        !python -W ignore scripts/demo_inference.py \
        --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x.yaml \
        --checkpoint ./shared_memory/pretrained_models/fast_res50_256x192.pth --detbatch 1 \
        --posebatch 24 --indir $indir --outdir $outdir --sp

        print('\n#### Start tracking....{}'.format(datetime.datetime.now()))

        !python -W ignore trackers/PoseFlow/tracker-general.py \
        --imgdir $indir \
        --in_json $outdir/alphapose-results.json \
        --out_json $outdir/alphapose-results-forvis-tracked.json     ". But when I run the program, it shows "/home/wxy/MoCoDAD-main/_annotations/AlphaPose
data
  0%|                                                     | 0/1 [00:00<?, ?it/s]
../shared_memory/data
../shared_memory/res/data/data
2024-09-16 14:30:57 [DEBUG]: Loaded backend agg version v2.2.
Loading YOLO model..
Loading pose model from ./shared_memory/pretrained_models/fast_res50_256x192.pth...
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00, 23.25it/s]
===========================> Finish Model Running.
Results have been written to json.ring remaining 0 images in the queue...

#### Start tracking....2024-09-16 14:31:00.992045
Start loading json file...

0.00it [00:00, ?it/s]
ORB matching frame pairs ...

0.00it [00:00, ?it/s]
Start pose tracking...

0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/wxy/MoCoDAD-main/_annotations/AlphaPose/trackers/PoseFlow/tracker-general.py", line 228, in <module>
    num_persons = max(num_persons, track[frame_name][pid]['new_pid'])
                                   ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'new_pid'
100%|█████████████████████████████████████████████| 1/1 [00:06<00:00,  6.15s/it]
res
  0%|                                                     | 0/1 [00:00<?, ?it/s]
../shared_memory/res
../shared_memory/res/res/res
2024-09-16 14:31:03 [DEBUG]: Loaded backend agg version v2.2.
[ WARN:0@1.087] global loadsave.cpp:241 findDecoder imread_('../shared_memory/res/alphapose-results-forvis.json'): can't open/read file: check file path/integrity
Exception in thread Thread-1 (image_preprocess):
Traceback (most recent call last):
  File "/home/wxy/anaconda3/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/wxy/anaconda3/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wxy/AlphaPose-master/alphapose/utils/detector.py", line 156, in image_preprocess
    img_k = self.detector.image_preprocess(im_name_k)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxy/AlphaPose-master/detector/yolo_api.py", line 69, in image_preprocess
    img, orig_img, im_dim_list = prep_image(img_source, self.inp_dim)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wxy/AlphaPose-master/detector/yolo/preprocess.py", line 42, in prep_image
    dim = orig_im.shape[1], orig_im.shape[0]
          ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'
Loading pose model from ./shared_memory/pretrained_models/fast_res50_256x192.pth...
  0%|                                                     | 0/2 [00:00<?, ?it/s]
". How do I solve them? Thank you very much!

**Comment by stdrr** [comment]
Dear @213pk, thank you for your interest in our work, and sorry for the late reply.

We are not actively maintaining the code for the dataset annotations, hence we don't guarantee that it will run properly. Furthermore, new updates of Alphapose and new models have been released in the meantime, so I would advise you to look at more recent works. If just the annotations of UBnormal are needed, we have released all the required files in the shared GDrive folder.

Best regards,
Stefano
