### ISSUE TITLE
Generate ground truth for UBnormal

### ISSUE THREAD

**Issue by 213pk** [aleflabo/MoCoDAD#22]
For the file "generate_annotations.ipynb" in the folder "_annotations", Could you provide the code for generating the ground truth for UBnormal dataset? I cannot generate a correct csv file for this dataset. Thanks!

**Comment by stdrr** [comment]
Dear @213pk, thank you for your interest in our work, and sorry for the late reply.

We are not actively maintaining the code for the dataset annotations, hence we don't guarantee that it will run properly. Furthermore, new updates of Alphapose and new models have been released in the meantime, so I would advise you to look at more recent works. If just the annotations of UBnormal are needed, we have released all the required files in the shared GDrive folder.

Best regards,
Stefano
