### ISSUE TITLE
Experiments and Implementation details

### ISSUE THREAD

**Issue by inaomIIsfarell** [aleflabo/MoCoDAD#23]
Hi aleflabo, thanks for your work !!!

When I was conducting the experiments for this paper, I found that my results were much different from those of the paper and the best weights you provides.

The experimental setup I use are provided in the [config](https://github.com/aleflabo/MoCoDAD/tree/main/config) in the repository, I use ``2 × nvidia p100`` for training and the results are following. I'd like to know what might be causing this, I would be very grateful if you could get back to me !
![result](https://github.com/user-attachments/assets/8a7d277a-2c59-493f-b4fd-f94f5f74478f)

**Comment by sssserious** [comment]
Hi, I have also encountered this problem recently. Is there any problem with my experiments? I tested on Ubnormal and trained 3 times. Each AUC was around 64-65. Is there any problem with my operation? , I use python trin_mocodad.py -config config/ubnormal/mocodad_train.yaml
