### ISSUE TITLE
How can I test HR-UBnormal?

### ISSUE THREAD

**Issue by SihuAhn** [aleflabo/MoCoDAD#8]
Hello, this project is awesome.
I'm testing your checkpoints. And ckecked HR-Avenue, HR-STC, and UBnormal.
However, I could find error about there is no UBnormal-hr_bool_masks-trajectories.
It can test only test_frame_mask? or how can I test HR-UBnormal?

**Comment by aleflabo** [comment]
Hi,

Can you post the error you're having here?

**Comment by SihuAhn** [comment]
I use provided UBnormal best_weights.ckpt.
and changed Paths in config.yaml.
![image](https://github.com/aleflabo/MoCoDAD/assets/59499464/0de7452b-912d-4a01-9608-156eee291d38)

however if I run eval_MoCoDAD.py , 
![image](https://github.com/aleflabo/MoCoDAD/assets/59499464/fe317dbd-430e-4d8e-ba89-6f0f49d189c4)
error is coming in data.py.

So, hr_bool_masks folder doesnt have trajectories.
It can evaluate only test_frame_mask?

**Comment by aleflabo** [comment]
the `data_dir` parameter should be just `./data/UBnormal/`

**Comment by SihuAhn** [comment]
Oh, I see.. It can run!  Thank you for your comments.

**Comment by SihuAhn** [comment]
After pred every samples, I get error in def post_processing in mocodad.py.
![image](https://github.com/aleflabo/MoCoDAD/assets/59499464/899f4da0-7617-49a2-9575-0315f43df418)

gt array is all True in HR-UBnormal case. Could you know how to solve this error? Why all hr_ubnormal_masked_clips are True?

**Comment by aleflabo** [comment]
It seems you're testing on the training set, where all the clips do not contain anomalies. 
Did you follow the steps to change the config in the [readme](https://github.com/aleflabo/MoCoDAD/tree/main#once-trained-you-can-run-the-evaluation)?
