### ISSUE TITLE
Train and evaluate with custom dataset

### ISSUE THREAD

**Issue by kaidn28** [aleflabo/MoCoDAD#9]
Hi, I wanna ask if there are any code versions which is available for training or testing on a custom dataset. It seems that the current code doesn't support this and the format of data is not stated.
It would be really helpful if you can give the code for converting to your data format, or a note on how to organize the data files to run the code. Thank you in advance!

**Comment by aleflabo** [comment]
Hi! 

We appreciate your interest in our work. We added a section for custom datasets in the readme (https://github.com/aleflabo/MoCoDAD/blob/main/README.md#custom-datasets-preparation). 

You can find the structure of the HR-UBnormal dataset here: https://drive.google.com/drive/u/1/folders/1h-dBNkAZdmgtlRd-TB8ScyHLshogTrLb
